# Existing properties...
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
file.upload-dir=uploads/profile-pictures

# Static Resource Configuration
spring.mvc.static-path-pattern=/uploads/**
spring.web.resources.static-locations=classpath:/static/,file:uploads/
spring.mvc.cors.max-age=3600

# Corrected DataSource URL
spring.datasource.url=jdbc:postgresql://dpg-d0cdnbali9vc73b81t80-a.oregon-postgres.render.com/noteably_db?user=noteably_db_user&password=Zh52m5C82QtLbgKS1BNmDaYQoC9Fk7Dz

# Setup datasource driver
spring.datasource.driver-class-name=org.postgresql.Driver
jwt.secret=u1v2w3x4y5z6A7B8C9D0E1F2G3H4I5J6K7L8M9N0O1P2Q3R4S5T6U7V8W9X0Y1Z2

# Database login credentials
spring.datasource.username=noteably_db_user
spring.datasource.password=Zh52m5C82QtLbgKS1BNmDaYQoC9Fk7Dz
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Auto-create tables based on entities
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.main.allow-circular-references=true

# For stack trace error not to appear
server.error.include-stacktrace=never
